"""Quorum: a classroom of AI models that debates hard questions and shows you
the fight.

The bet is not that three models produce a better answer than one. It is that
*where independent models diverge is where the real uncertainty lives*, and
that a decision-maker who can see the argument — the objections, the
mind-changes, the dissent that did not make the final answer — decides better
than one handed a single fluent paragraph. The transcript is the product.

    from quorum import demo_council, mock_pool, convene

    council = demo_council()
    result = convene("Should we rebuild or refactor?", council, mock_pool(council))
    print(result.verdict.final_answer)
    print(result.stats())
"""

from .blinding import LABELS, BlindingRound, blind_map, build_blinding, invert
from .council import (
    MAX_STUDENTS,
    MIN_STUDENTS,
    Council,
    CouncilError,
    ModelCost,
    Seat,
    demo_council,
)
from .prompts import (
    CRITIQUE_PROMPT_HEADER,
    PROBE_PROMPT_HEADER,
    SKEPTIC_INSTRUCTION,
    build_probe_prompt,
    build_skeptic_critique_prompt,
    leading_sheet_label,
    REVISION_PROMPT_HEADER,
    SHEET_PROMPT_HEADER,
    VERDICT_PROMPT_HEADER,
    build_critique_prompt,
    build_revision_prompt,
    build_sheet_prompt,
    build_verdict_prompt,
    render_sheet,
)
from .providers.http import AnthropicProvider, OpenAICompatibleProvider
from .providers.base import (
    Completion,
    FlakyProvider,
    MockProvider,
    Provider,
    ProviderConfigError,
    ProviderError,
    ProviderPool,
    ProviderRateLimited,
    ProviderTimeout,
    ProviderUnavailable,
    ScriptedProvider,
    mock_pool,
)
from .convening import (
    CONVENE_ALWAYS,
    CONVENE_CONSERVATIVE,
    CONVENE_DEFAULT,
    JUDGMENT_TYPES,
    CONVENE_NEVER,
    CONVENING_PRESETS,
    ConveneDecision,
    ConveningPolicy,
    Task,
    TaskSignals,
    VERIFIABLE_TYPES,
    should_convene,
    signals,
)
from .benchmark import (
    ARMS,
    ArmResult,
    BenchmarkMockProvider,
    BenchmarkReport,
    Criterion,
    JudgmentTask,
    TaskOutcome,
    load_tasks,
    run_benchmark,
)
from .costs import Baseline, cost_multiple, pick_baseline_seat, single_model_baseline
from .divergence import Disagreement, disagreement
from .probe import (
    Guess,
    PROBER,
    ProbeError,
    ProbeReport,
    ProbeResult,
    probe_all,
    probe_session,
)
from .replay import ReplayedSession, render, replay, replay_file
from .report import (
    RankedObjection,
    rank_objections,
    render_html,
    render_markdown,
    write_report,
)
from .session import (
    Absence,
    Objection,
    Session,
    SessionConfig,
    SessionResult,
    StudentRecord,
    build_transcript,
    convene,
)
from .sheets import (
    MAX_CLAIMS,
    MIN_ARGUMENT_CHARS,
    AnswerSheet,
    Claim,
    ClaimEdit,
    MinorityItem,
    NonCompliantCritique,
    ObjectionRef,
    RawObjection,
    Revision,
    SheetDiff,
    SheetError,
    SheetParseError,
    SheetSchemaError,
    Verdict,
    diff_sheets,
    extract_json,
    parse_critique,
    parse_revision,
    parse_sheet,
    parse_verdict,
)
from .trace import EVENT_TYPES, TraceEvent, TraceWriter, group_sessions, read_trace

__version__ = "0.1.0"

__all__ = [
    "ARMS",
    "Absence",
    "AnswerSheet",
    "AnthropicProvider",
    "ArmResult",
    "Baseline",
    "BenchmarkMockProvider",
    "BenchmarkReport",
    "BlindingRound",
    "CONVENE_ALWAYS",
    "CONVENE_CONSERVATIVE",
    "CONVENE_DEFAULT",
    "CONVENE_NEVER",
    "CONVENING_PRESETS",
    "CRITIQUE_PROMPT_HEADER",
    "Claim",
    "ClaimEdit",
    "Completion",
    "ConveneDecision",
    "ConveningPolicy",
    "Council",
    "CouncilError",
    "Criterion",
    "Disagreement",
    "EVENT_TYPES",
    "FlakyProvider",
    "Guess",
    "JUDGMENT_TYPES",
    "JudgmentTask",
    "LABELS",
    "MAX_CLAIMS",
    "MAX_STUDENTS",
    "MIN_ARGUMENT_CHARS",
    "MIN_STUDENTS",
    "MinorityItem",
    "MockProvider",
    "ModelCost",
    "NonCompliantCritique",
    "Objection",
    "ObjectionRef",
    "OpenAICompatibleProvider",
    "PROBER",
    "PROBE_PROMPT_HEADER",
    "ProbeError",
    "ProbeReport",
    "ProbeResult",
    "Provider",
    "ProviderConfigError",
    "ProviderError",
    "ProviderPool",
    "ProviderRateLimited",
    "ProviderTimeout",
    "ProviderUnavailable",
    "REVISION_PROMPT_HEADER",
    "RankedObjection",
    "RawObjection",
    "ReplayedSession",
    "Revision",
    "SHEET_PROMPT_HEADER",
    "SKEPTIC_INSTRUCTION",
    "ScriptedProvider",
    "Seat",
    "Session",
    "SessionConfig",
    "SessionResult",
    "SheetDiff",
    "SheetError",
    "SheetParseError",
    "SheetSchemaError",
    "StudentRecord",
    "Task",
    "TaskOutcome",
    "TaskSignals",
    "TraceEvent",
    "TraceWriter",
    "VERDICT_PROMPT_HEADER",
    "VERIFIABLE_TYPES",
    "Verdict",
    "blind_map",
    "build_blinding",
    "build_critique_prompt",
    "build_probe_prompt",
    "build_revision_prompt",
    "build_sheet_prompt",
    "build_skeptic_critique_prompt",
    "build_transcript",
    "build_verdict_prompt",
    "convene",
    "cost_multiple",
    "demo_council",
    "diff_sheets",
    "disagreement",
    "extract_json",
    "group_sessions",
    "invert",
    "leading_sheet_label",
    "load_tasks",
    "mock_pool",
    "parse_critique",
    "parse_revision",
    "parse_sheet",
    "parse_verdict",
    "pick_baseline_seat",
    "probe_all",
    "probe_session",
    "rank_objections",
    "read_trace",
    "render",
    "render_html",
    "render_markdown",
    "render_sheet",
    "replay",
    "replay_file",
    "run_benchmark",
    "should_convene",
    "signals",
    "single_model_baseline",
    "write_report",
]
